[window]

startup_mode = "Maximized"

padding = { x = 20, y = 20 }

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 16

[colors]

    [colors.primary]
    # hard contrast: background = '0x1d2021'
        background = "#282828"
    # soft contrast: background = '0x32302f'
        foreground = "#ebdbb2"

  # Normal colors
    [colors.normal]
        black =   "#282828"
        red =     "#cc241d"
        green =   "#98971a"
        yellow =  "#d79921"
        blue =    "#458588"
        magenta = "#b16286"
        cyan =    "#689d6a"
        white =   "#a89984"

  # Bright colors
    [colors.bright]
        black =   "#928374"
        red =     "#fb4934"
        green =   "#b8bb26"
        yellow =  "#fabd2f"
        blue =    "#83a598"
        magenta = "#d3869b"
        cyan =    "#8ec07c"
        white =   "#ebdbb2"
